import { Dimensions, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');

//innerSize priority Visible ; OuterSize priority @WallRuled
export const outerSizes = (theme) => StyleSheet.create({
  // ================ Box Sizing ================
  boxSizingborder: { boxSizing: 'border-box' },
  boxSizingcontent: { boxSizing: 'content-box' },
  
    //fitting
  outerfit:{maxWidth:width, maxHeight:height },
  outerfitauto:{maxWidth:width, maxHeight:'auto' },
  outerfitfull:{maxWidth:width, maxHeight:'100%' },

  // full
  outerfull:{maxWidth: '100%', maxHeight: '100%' },
  outerfullauto:{maxWidth: '100%', maxHeight: 'auto' },
  outerfullfit:{maxWidth: '100%', maxHeight:height },

  // auto 
  outerauto:{maxWidth: 'auto', maxHeight: 'auto' },
  outerautofit:{maxWidth: 'auto', maxHeight:height },
  outerautofull:{maxWidth: 'auto', maxHeight: '100%' },

  // ================ maxWidth Utilities ================
  // Fixed maxWidths
  outerWPx05: { maxWidth:.5 },
  outerWPx1: { maxWidth: theme.space[1] || 4 },
  outerWPx2: { maxWidth: theme.space[2] || 8 },
  outerWPx3: { maxWidth: theme.space[3] || 12 },
  outerWPx4: { maxWidth: theme.space[4] || 16 },
  outerWPx5: { maxWidth: theme.space[5] || 20 },
  outerWPx6: { maxWidth: theme.space[6] || 24 },
  outerWPx7: { maxWidth: theme.space[7] || 28 },
  outerWPx8: { maxWidth: theme.space[8] || 32 },
  outerWPx9: { maxWidth: theme.space[9] || 36 },
  outerWPx10: { maxWidth: theme.space[10] || 40 },
  outerWPx11: { maxWidth: theme.space[11] || 44 },
  outerWPx12: { maxWidth: theme.space[12] || 48 },
  outerWPx14: { maxWidth: theme.space[14] || 56 },
  outerWPx16: { maxWidth: theme.space[16] || 64 },
  outerWPx20: { maxWidth: theme.space[20] || 80 },
  outerWPx24: { maxWidth: theme.space[24] || 96 },
  outerWPx28: { maxWidth: theme.space[28] || 112 },
  outerWPx32: { maxWidth: theme.space[32] || 128 },
  outerWPx36: { maxWidth: theme.space[36] || 144 },
  outerWPx40: { maxWidth: theme.space[40] || 160 },
  outerWPx44: { maxWidth: theme.space[44] || 176 },
  outerWPx48: { maxWidth: theme.space[48] || 192 },
  outerWPx52: { maxWidth: theme.space[52] || 208 },
  outerWPx56: { maxWidth: theme.space[56] || 224 },
  outerWPx60: { maxWidth: theme.space[60] || 240 },
  outerWPx64: { maxWidth: theme.space[64] || 256 },
  outerWPx72: { maxWidth: theme.space[72] || 288 },
  outerWPx80: { maxWidth: theme.space[80] || 320 },
  outerWPx96: { maxWidth: theme.space[96] || 384 },
  
    // Fixed maxHeights
  outerHPx05: { maxHeight: .5 },
  outerHPx1: { maxHeight: theme.space[1] || 4 },
  outerHPx2: { maxHeight: theme.space[2] || 8 },
  outerHPx3: { maxHeight: theme.space[3] || 12 },
  outerHPx4: { maxHeight: theme.space[4] || 16 },
  outerHPx5: { maxHeight: theme.space[5] || 20 },
  outerHPx6: { maxHeight: theme.space[6] || 24 },
  outerHPx7: { maxHeight: theme.space[7] || 28 },
  outerHPx8: { maxHeight: theme.space[8] || 32 },
  outerHPx9: { maxHeight: theme.space[9] || 36 },
  outerHPx10: { maxHeight: theme.space[10] || 40 },
  outerHPx11: { maxHeight: theme.space[11] || 44 },
  outerHPx12: { maxHeight: theme.space[12] || 48 },
  outerHPx14: { maxHeight: theme.space[14] || 56 },
  outerHPx16: { maxHeight: theme.space[16] || 64 },
  outerHPx20: { maxHeight: theme.space[20] || 80 },
  outerHPx24: { maxHeight: theme.space[24] || 96 },
  outerHPx28: { maxHeight: theme.space[28] || 112 },
  outerHPx32: { maxHeight: theme.space[32] || 128 },
  outerHPx36: { maxHeight: theme.space[36] || 144 },
  outerHPx40: { maxHeight: theme.space[40] || 160 },
  outerHPx44: { maxHeight: theme.space[44] || 176 },
  outerHPx48: { maxHeight: theme.space[48] || 192 },
  outerHPx52: { maxHeight: theme.space[52] || 208 },
  outerHPx56: { maxHeight: theme.space[56] || 224 },
  outerHPx60: { maxHeight: theme.space[60] || 240 },
  outerHPx64: { maxHeight: theme.space[64] || 256 },
  outerHPx72: { maxHeight: theme.space[72] || 288 },
  outerHPx80: { maxHeight: theme.space[80] || 320 },
  outerHPx96: { maxHeight: theme.space[96] || 384 },


    //100Sections of Parent()
    
  // percent
    outerWPr100: { maxWidth: '100%' },
    outerWPr95: { maxWidth: '95%' },
    outerWPr90: { maxWidth: '90%' },
    outerWPr85: { maxWidth: '85%' },
    outerWPr80: { maxWidth: '80%' },
    outerWPr75: { maxWidth: '75%' },
    outerWPr70: { maxWidth: '70%' },
    outerWPr65: { maxWidth: '65%' },
    outerWPr60: { maxWidth: '60%' },
    outerWPr55: { maxWidth: '55%' },
    outerWPr50: { maxWidth: '550%' },
    outerWPr45: { maxWidth: '45%' },
    outerWPr40: { maxWidth: '40%' },
    outerWPr35: { maxWidth: '35%' },
    outerWPr30: { maxWidth: '30%' },
    outerWPr25: { maxWidth: '25%' },
    outerWPr20: { maxWidth: '20%' },
    outerWPr15: { maxWidth: '15%' },
    outerWPr10: { maxWidth: '10%' },
    outerWPr5: { maxWidth: '5%' },
    outerWPr1: { maxWidth: '1%' },


    outerHPr100: { maxHeight: '100%' },
    outerHPr95: { maxHeight: '95%' },
    outerHPr90: { maxHeight: '90%' },
    outerHPr85: { maxHeight: '85%' },
    outerHPr80: { maxHeight: '80%' },
    outerHPr75: { maxHeight: '75%' },
    outerHPr70: { maxHeight: '70%' },
    outerHPr65: { maxHeight: '65%' },
    outerHPr60: { maxHeight: '60%' },
    outerHPr55: { maxHeight: '55%' },
    outerHPr50: { maxHeight: '550%' },
    outerHPr45: { maxHeight: '45%' },
    outerHPr40: { maxHeight: '40%' },
    outerHPr35: { maxHeight: '35%' },
    outerHPr30: { maxHeight: '30%' },
    outerHPr25: { maxHeight: '25%' },
    outerHPr20: { maxHeight: '20%' },
    outerHPr15: { maxHeight: '15%' },
    outerHPr10: { maxHeight: '10%' },
    outerHPr5: { maxHeight: '5%' },
    outerHPr1: { maxHeight: '1%' },
  
    //100Sections of Screen(Windows)
      // percent
    outerWVp100: { maxWidth: '100vw' },
    outerWVp95: { maxWidth: '95vw' },
    outerWVp90: { maxWidth: '90vw' },
    outerWVp85: { maxWidth: '85vw' },
    outerWVp80: { maxWidth: '80vw' },
    outerWVp75: { maxWidth: '75vw' },
    outerWVp70: { maxWidth: '70vw' },
    outerWVp65: { maxWidth: '65vw' },
    outerWVp60: { maxWidth: '60vw' },
    outerWVp55: { maxWidth: '55vw' },
    outerWVp50: { maxWidth: '550vw' },
    outerWVp45: { maxWidth: '45vw' },
    outerWVp40: { maxWidth: '40vw' },
    outerWVp35: { maxWidth: '35vw' },
    outerWVp30: { maxWidth: '30vw' },
    outerWVp25: { maxWidth: '25vw' },
    outerWVp20: { maxWidth: '20vw' },
    outerWVp15: { maxWidth: '15vw' },
    outerWVp10: { maxWidth: '10vw' },
    outerWVp5: { maxWidth: '5vw' },
    outerWVp1: { maxWidth: '1vw' },


    outerHVp100: { maxHeight: '100vh' },
    outerHVp95: { maxHeight: '95vh' },
    outerHVp90: { maxHeight: '90vh' },
    outerHVp85: { maxHeight: '85vh' },
    outerHVp80: { maxHeight: '80vh' },
    outerHVp75: { maxHeight: '75vh' },
    outerHVp70: { maxHeight: '70vh' },
    outerHVp65: { maxHeight: '65vh' },
    outerHVp60: { maxHeight: '60vh' },
    outerHVp55: { maxHeight: '55vh' },
    outerHVp50: { maxHeight: '550vh' },
    outerHVp45: { maxHeight: '45vh' },
    outerHVp40: { maxHeight: '40vh' },
    outerHVp35: { maxHeight: '35vh' },
    outerHVp30: { maxHeight: '30vh' },
    outerHVp25: { maxHeight: '25vh' },
    outerHVp20: { maxHeight: '20vh' },
    outerHVp15: { maxHeight: '15vh' },
    outerHVp10: { maxHeight: '10vh' },
    outerHVp5: { maxHeight: '5vh' },
    outerHVp1: { maxHeight: '1vh' },

});

export default outerSizes
