name: Setup Project Structure

on:
  workflow_dispatch:  # Manual only
  push:
    branches: [main]
    paths: ['scripts/setup-folders.js']  # Run when setup script changes

jobs:
  setup-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Create project structure
        run: node scripts/setup-folders.js
        
      - name: Commit structure changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: update project structure" || exit 0
          git push